# Generated by Django 4.0.5 on 2022-09-12 06:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web_base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipovehiculo',
            name='cod_vehiculo',
            field=models.CharField(default='Elegir cod', max_length=100, verbose_name='Código vehículo'),
        ),
        migrations.AddField(
            model_name='tipovehiculo',
            name='creado_el',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creado el'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipovehiculo',
            name='tipo_vehiculo',
            field=models.CharField(default='Elegir tipo', max_length=100, verbose_name='Tipo vehículo'),
        ),
    ]
