# Generated by Django 4.0.5 on 2022-09-12 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_base', '0002_tipovehiculo_cod_vehiculo_tipovehiculo_creado_el_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipovehiculo',
            name='creado_el',
        ),
        migrations.AlterField(
            model_name='tipovehiculo',
            name='cod_vehiculo',
            field=models.CharField(max_length=100, verbose_name='Código vehículo'),
        ),
        migrations.AlterField(
            model_name='tipovehiculo',
            name='tipo_vehiculo',
            field=models.CharField(max_length=100, verbose_name='Tipo vehículo'),
        ),
    ]
