# Generated by Django 4.0.5 on 2022-09-12 06:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web_base', '0003_remove_tipovehiculo_creado_el_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipovehiculo',
            name='creado_el',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creado el'),
            preserve_default=False,
        ),
    ]
