# Generated by Django 4.0.5 on 2022-09-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_base', '0004_tipovehiculo_creado_el'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPoliza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_poliza', models.CharField(max_length=100, verbose_name='Código póliza')),
                ('tipo_poliza', models.CharField(max_length=100, verbose_name='Tipo póliza')),
                ('creado_el', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
            ],
        ),
        migrations.CreateModel(
            name='TipoSiniestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_siniestro', models.CharField(max_length=100, verbose_name='Código siniestro')),
                ('tipo_siniestro', models.CharField(max_length=100, verbose_name='Tipo siniestro')),
                ('creado_el', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
            ],
        ),
    ]
