# Generated by Django 4.0.5 on 2022-09-12 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_base', '0006_marca_alter_tipopoliza_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marca',
            options={'ordering': ['marca'], 'verbose_name': 'Marca', 'verbose_name_plural': 'Marcas'},
        ),
    ]
