# Generated by Django 4.0.5 on 2022-09-12 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_base', '0007_alter_marca_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_modelo', models.CharField(max_length=100, verbose_name='Código siniestro')),
                ('modelo', models.CharField(max_length=100, verbose_name='Tipo siniestro')),
                ('creado_el', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('marca_modelo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web_base.marca')),
            ],
            options={
                'verbose_name': 'Modelo vehículo',
                'verbose_name_plural': 'Modelos de vehículo',
                'ordering': ['modelo'],
            },
        ),
    ]
