# Generated by Django 4.0.5 on 2022-09-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_base', '0008_modelovehiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelovehiculo',
            name='cod_modelo',
            field=models.CharField(max_length=100, verbose_name='Código modelo'),
        ),
        migrations.AlterField(
            model_name='modelovehiculo',
            name='modelo',
            field=models.CharField(max_length=100, verbose_name='Modelo vehículo'),
        ),
    ]
