# Generated by Django 4.0.5 on 2022-09-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_base', '0009_alter_modelovehiculo_cod_modelo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablaSiniestros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_conductor', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido_conductor', models.CharField(max_length=100, verbose_name='Apellido')),
                ('rut_conductor', models.CharField(max_length=100, verbose_name='Rut')),
                ('fecha_siniestro', models.DateField(verbose_name='Fecha siniestro')),
                ('descripcion_siniestro', models.TextField(max_length=300, verbose_name='Descripción siniestro')),
            ],
            options={
                'verbose_name': 'Siniestro',
                'verbose_name_plural': 'BD Siniestros',
                'ordering': ['rut_conductor'],
            },
        ),
    ]
