# Generated by Django 4.0.5 on 2022-09-13 06:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web_base', '0010_tablasiniestros'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablasiniestros',
            name='edad_conductor',
            field=models.IntegerField(default='18', verbose_name='Edad conductor(a)'),
        ),
        migrations.AddField(
            model_name='tablasiniestros',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha registro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tablasiniestros',
            name='nombre_marca',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='web_base.marca'),
        ),
        migrations.AddField(
            model_name='tablasiniestros',
            name='nombre_modelo',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='web_base.modelovehiculo'),
        ),
        migrations.AddField(
            model_name='tablasiniestros',
            name='tipo_de_poliza',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='web_base.tipopoliza'),
        ),
        migrations.AddField(
            model_name='tablasiniestros',
            name='tipo_de_siniestro',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='web_base.tiposiniestro'),
        ),
        migrations.AddField(
            model_name='tablasiniestros',
            name='tipo_de_vehiculo',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='web_base.tipovehiculo'),
        ),
        migrations.AlterField(
            model_name='tablasiniestros',
            name='apellido_conductor',
            field=models.CharField(max_length=100, verbose_name='Apellido conductor(a)'),
        ),
        migrations.AlterField(
            model_name='tablasiniestros',
            name='nombre_conductor',
            field=models.CharField(max_length=100, verbose_name='Nombre conductor(a)'),
        ),
        migrations.AlterField(
            model_name='tablasiniestros',
            name='rut_conductor',
            field=models.CharField(max_length=100, verbose_name='Rut conductor(a)'),
        ),
    ]
