# Generated by Django 4.0.5 on 2022-09-13 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_base', '0011_tablasiniestros_edad_conductor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablaDeSiniestros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre conductor(a)')),
                ('tipo_de_modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_base.modelovehiculo')),
                ('tipo_de_siniestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_base.tiposiniestro')),
            ],
            options={
                'verbose_name': 'SN',
                'verbose_name_plural': 'SNS',
            },
        ),
    ]
