# Generated by Django 4.0.5 on 2022-09-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_base', '0013_alter_tabladesiniestros_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataBaseUsuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(choices=[('Administrdor', 'Administrdor'), ('Liquidador', 'Liquidador'), ('Cliente', 'Cliente')], max_length=50)),
            ],
        ),
    ]
