# Generated by Django 4.0.5 on 2022-09-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_base', '0014_databaseusuarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseusuarios',
            name='apellido_usuario',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='databaseusuarios',
            name='cargo_usuario',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='databaseusuarios',
            name='nombre_usuario',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='databaseusuarios',
            name='tipo_usuario',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Liquidador', 'Liquidador'), ('Cliente', 'Cliente')], max_length=50),
        ),
    ]
