# Generated by Django 4.0.5 on 2022-09-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_base', '0015_databaseusuarios_apellido_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseusuarios',
            name='mail_usuario',
            field=models.EmailField(default='@liquidaya.com', max_length=100),
        ),
    ]
