# Generated by Django 4.0.5 on 2022-09-18 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_base', '0016_databaseusuarios_mail_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='databaseusuarios',
            options={'ordering': ['-apellido_usuario']},
        ),
    ]
