# Generated by Django 4.0.5 on 2022-09-19 14:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web_base', '0017_alter_databaseusuarios_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='databaseusuarios',
            options={'ordering': ['tipo_usuario', 'apellido_usuario']},
        ),
        migrations.AddField(
            model_name='tabladesiniestros',
            name='updated_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha siniestro'),
        ),
    ]
