# Generated by Django 4.0.5 on 2022-09-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_base', '0018_alter_databaseusuarios_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabladesiniestros',
            name='updated_at',
            field=models.DateField(verbose_name='Última actualización'),
        ),
    ]
