# Generated by Django 4.0.5 on 2022-09-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_base', '0019_alter_tabladesiniestros_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabladesiniestros',
            name='updated_at',
            field=models.DateField(auto_now_add=True, verbose_name='Última actualización'),
        ),
    ]
