# Generated by Django 4.0.5 on 2022-09-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_base', '0020_alter_tabladesiniestros_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabladesiniestros',
            name='estado_siniestro',
            field=models.CharField(choices=[('Ingresado', 'Ingresado'), ('Aprobado', 'Aprobado'), ('En reparación', 'En reparación'), ('En entrega', 'En entrega'), ('Cerrada', 'Cerrada'), ('Indidencia', 'Indidencia')], default='Ingresado', max_length=50),
        ),
    ]
