# Generated by Django 4.0.5 on 2022-09-20 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web_base', '0022_alter_tabladesiniestros_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabladesiniestros',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
