# Generated by Django 4.0.5 on 2022-09-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_base', '0023_tabladesiniestros_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabladesiniestros',
            name='estado_siniestro',
            field=models.CharField(choices=[('Ingresado', 'Ingresado'), ('Aprobado', 'Aprobado'), ('En reparación', 'En reparación'), ('En entrega', 'En entrega'), ('Cerrada', 'Cerrada'), ('Incidencia', 'Incidencia')], default='Ingresado', max_length=50),
        ),
    ]
