# Generated by Django 4.1.1 on 2022-10-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_base', '0026_alter_tabladesiniestros_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_contacto', models.CharField(max_length=100)),
                ('apellido_contacto', models.CharField(max_length=100)),
                ('email_contacto', models.EmailField(max_length=100)),
                ('texto_contacto', models.TextField(max_length=400)),
            ],
        ),
    ]
